services:
  mysql_container:
    image: mysql:8.0
    platform: linux/amd64  # Hoặc linux/arm64 nếu bạn dùng Mac M1/M2
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_net

  wordpress_container:
    image: wordpress:latest
    platform: linux/amd64
    container_name: wordpress_container
    restart: always
    depends_on:
      - mysql_container
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql_container:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp_net

volumes:
  db_data:
  wp_data:

networks:
  wp_net:
