services:
  app1:
    build: ./app1
    container_name: app1
    networks:
      - mynetwork

  app2:
    build: ./app2
    container_name: app2
    depends_on:
      - app1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
