services:
  flask1:
    build: ./flask
    ports:
      - "5001:5000"
  flask2:
    build: ./flask
    ports:
      - "5002:5000"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask1
      - flask2
