
services:
  postgres:
    image: postgres:13
    container_name: pg-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8083:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
